/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me_opencv_OpencvTest */

#ifndef _Included_com_me_opencv_OpencvTest
#define _Included_com_me_opencv_OpencvTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_opencv_OpencvTest
 * Method:    opencvCapture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_me_opencv_OpencvTest_opencvCapture
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
